### ISSUE TITLE
crashes on GTA V version 2699.16

### ISSUE THREAD

**Issue by 0x-FADED** [Dilapidated/PoolManager#4]
when playing with poolmanager the game starts and after 2 or 3 minutes into the game it crashes. no clue why this is happening and the debugger isn't also hitting anything.

**Comment by Dilapidated** [comment]
I'm seeing the same issue. I'm guessing some of the patterns need fixed.

**Comment by Dilapidated** [comment]
This has been fixed: https://github.com/Dilapidated/PoolManager/commit/703f5a76511cdf3e79f89db934dd7df59eb57238

The culprit pool ended up being 0x5F91F738 = netshoptransactions
It's unknown if some anti-tampering code was added. The pool is ignored for now to avoid this crash.
