### ISSUE TITLE
Wrong name?

### ISSUE THREAD

**Issue by zzzz5116** [Dilapidated/PoolManager#6]
![0$06VIW59LJ7`YJG3MCURZJ](https://user-images.githubusercontent.com/76660035/221401660-d0c30a5a-6c91-4a2f-b89a-d73e1308566e.png)
The displayed pool name is not the same as the actual related pool name, I'm pretty sure it's "HandlingData" that's causing the crash

**Comment by 0x-FADED** [comment]
No you just need to create a new pool in the XML and call it chandlingobject and increase it's value that's all

**Comment by Michael21107** [comment]
@Dilapidated

**Comment by isdzjfs** [comment]
> No you just need to create a new pool in the XML and call it chandlingobject and increase it's value that's all

You are right, I tested the method you said and it works, but I also tried just increasing the value of "HandlingData" and it works too, which is weird

**Comment by zzzz5116** [comment]
> No you just need to create a new pool in the XML and call it chandlingobject and increase it's value that's all

You are right, I tested the method you said and it works, but I also tried just increasing the value of "HandlingData" and it works too, which is weird
